services:
  backend:
    container_name: backend
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    ports:
      - "5000:80"
    networks:
      - app-network

  db:
    container_name: db
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=test
     - MYSQL_HOST=db
     - MYSQL_DATABASE=app_db
     - MYSQL_USER=test
     - MYSQL_PASSWORD=test
     - MYSQL_CHARSET=utf8
     - TZ=Asia/Tokyo
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge